### ISSUE TITLE
Override styles

### ISSUE THREAD

**Issue by nikolay-borzov** [jocodev1/vue-muuri#1]
Is it really necessary to add default visual styles like this?
```
  .item {
    // display: block;
    // position: absolute;
    margin: 5px;
    // z-index: 1;
    background: #333;
    border: 2px solid black;
    border-radius: 5px;
    padding: 15px;
    color: #fff;
    opacity: 0.9;
  }
```
The only way to override `.item` padding is
```
.item[data-v-6ac0860c] {
  padding: 0;
}
```

I think we only need styles that are required for muuri

**Comment by jocodev1** [comment]
@nikolay-borzov  Thanks for the suggestion. I will change the styles to be the default muuri styles.

Until I update, couldn't you override this way?

`.item { padding: 0 !important }`

**Comment by jocodev1** [comment]
@nikolay-borzov  This has been updated in the latest release v0.1.2

**Comment by nikolay-borzov** [comment]
Thanks a lot!
