### ISSUE TITLE
v-for

### ISSUE THREAD

**Issue by dscummings** [jocodev1/vue-muuri#7]
How would 'v-for' be used with this to display items within the grid dynamically from a database? I'm having trouble getting this to work. Any advice?

**Comment by jocodev1** [comment]
@dscummings sorry for the late reply...

You would essentially do this the same way you would loop through a basic div element with v-for, but first you have to make an ajax call to retrieve your data. Once you have your data, you'll use v-for on any of the grid item components.

I have a similar example in the README, but here is a more guided example.

```
<item-sm v-for="item, index in dbData">
   <p>{{ item.name }}</p>
</item-sm>
```

```js
// ...
data () {
  return  {
     dbData: []
  }
},
mounted: {
  this.fetchData()
},
methods: {
  fetchData () {
     // make ajax call
    let self = this
    axios({
       url: 'YOUR-URL',
       method: 'GET'
    }).then((response) => {
       self.dbData = response.data
    })
  }
}
```
